### ISSUE TITLE
Issue with predictions in Google Colab

### ISSUE THREAD

**Issue by tldirkse-nl** [haberlmatt/cdeep3m-colab#4]
I keep getting "list index out of range" errors when running the code cell for the predictions in Google Colab ("Prediction GUI" notebook). It generates the following output:

Image enhancements completed
Enhanced images are stored in/home/predictout//enhanced
Starting Image Augmentation:
Check image size of:  /home/predictout//enhanced
Reading file:  /home/predictout//enhanced/2929Q1_06217.png
Start up worker to generate packages to process
Start up worker to run prediction on packages
Start up worker to run post processing on packages

To see progress run the following command in another window:

tail -f /home/predictout//logs/*.log
['/home/cdeep3m/Create_overlays.py', '/home/predictout//ensembled', '/home/predictout//enhanced', '/home/predictout//overlay']
Processing 14 images 
Running 1 parallel tasks
Traceback (most recent call last):
  File "/home/cdeep3m/Create_overlays.py", line 73, in <module>
    results = Parallel(n_jobs=p_tasks)(delayed(processInput)(i) for i in range(0, len(file_list_raw)))
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.7/dist-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/usr/local/lib/python3.7/dist-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/usr/local/lib/python3.7/dist-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/cdeep3m/Create_overlays.py", line 45, in processInput
    file_in = os.path.join(inputfolder_seg, file_list_seg[x])
IndexError: list index out of range
ERROR, a non-zero exit code (1) was received from: Create_overlays.py /home/predictout//ensembled /home/predictout//enhanced /home/predictout//overlay

**Comment by haberlmatt** [comment]
i think it is resolved, re-open if needed
